/*
 * API's OpenData do Open Banking Brasil
 *
 * As API's descritas neste documento são referentes as API's da fase OpenData do Open Banking Brasil.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: apiteam@swagger.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace BGB.OpenBanking.Api.Areas.Common.Models
{ 
        /// <summary>
        /// Sigla de identificação do Serviço Prioritário, segundo Resolução 3.919 do Bacen.
        /// </summary>
        /// <value>Sigla de identificação do Serviço Prioritário, segundo Resolução 3.919 do Bacen.</value>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum AccountPriorityServiceCode
        {
            /// <summary>
            /// Enum CADASTROEnum for CADASTRO
            /// </summary>
            [EnumMember(Value = "CADASTRO")]
            CADASTROEnum = 0,
            /// <summary>
            /// Enum _2VIACARTAODEBITOEnum for 2_VIA_CARTAO_DEBITO
            /// </summary>
            [EnumMember(Value = "2_VIA_CARTAO_DEBITO")]
            _2VIACARTAODEBITOEnum = 1,
            /// <summary>
            /// Enum _2VIACARTAOPOUPANCAEnum for 2_VIA-CARTAO_POUPANCA
            /// </summary>
            [EnumMember(Value = "2_VIA-CARTAO_POUPANCA")]
            _2VIACARTAOPOUPANCAEnum = 2,
            /// <summary>
            /// Enum EXCLUSAOCCFEnum for EXCLUSAO_CCF
            /// </summary>
            [EnumMember(Value = "EXCLUSAO_CCF")]
            EXCLUSAOCCFEnum = 3,
            /// <summary>
            /// Enum SUSTACAOREVOGACAOEnum for SUSTACAO_REVOGACAO
            /// </summary>
            [EnumMember(Value = "SUSTACAO_REVOGACAO")]
            SUSTACAOREVOGACAOEnum = 4,
            /// <summary>
            /// Enum FOLHACHEQUEEnum for FOLHA_CHEQUE
            /// </summary>
            [EnumMember(Value = "FOLHA_CHEQUE")]
            FOLHACHEQUEEnum = 5,
            /// <summary>
            /// Enum CHEQUEADMINISTRATIVOEnum for CHEQUE_ADMINISTRATIVO
            /// </summary>
            [EnumMember(Value = "CHEQUE_ADMINISTRATIVO")]
            CHEQUEADMINISTRATIVOEnum = 6,
            /// <summary>
            /// Enum CHEQUEVISADOEnum for CHEQUE_VISADO
            /// </summary>
            [EnumMember(Value = "CHEQUE_VISADO")]
            CHEQUEVISADOEnum = 7,
            /// <summary>
            /// Enum SAQUEPESSOALEnum for SAQUE_PESSOAL
            /// </summary>
            [EnumMember(Value = "SAQUE_PESSOAL")]
            SAQUEPESSOALEnum = 8,
            /// <summary>
            /// Enum SAQUETERMINALEnum for SAQUE_TERMINAL
            /// </summary>
            [EnumMember(Value = "SAQUE_TERMINAL")]
            SAQUETERMINALEnum = 9,
            /// <summary>
            /// Enum SAQUECORRESPONDENTEEnum for SAQUE_CORRESPONDENTE
            /// </summary>
            [EnumMember(Value = "SAQUE_CORRESPONDENTE")]
            SAQUECORRESPONDENTEEnum = 10,
            /// <summary>
            /// Enum DEPOSITOIDENTIFICADOEnum for DEPOSITO_IDENTIFICADO
            /// </summary>
            [EnumMember(Value = "DEPOSITO_IDENTIFICADO")]
            DEPOSITOIDENTIFICADOEnum = 11,
            /// <summary>
            /// Enum EXTRATOMESPEnum for EXTRATO_MES_P
            /// </summary>
            [EnumMember(Value = "EXTRATO_MES_P")]
            EXTRATOMESPEnum = 12,
            /// <summary>
            /// Enum EXTRATOMESEEnum for EXTRATO_MES_E
            /// </summary>
            [EnumMember(Value = "EXTRATO_MES_E")]
            EXTRATOMESEEnum = 13,
            /// <summary>
            /// Enum EXTRATOMESCEnum for EXTRATO_MES_C
            /// </summary>
            [EnumMember(Value = "EXTRATO_MES_C")]
            EXTRATOMESCEnum = 14,
            /// <summary>
            /// Enum EXTRATOMOVIMENTOPEnum for EXTRATO_MOVIMENTO_P
            /// </summary>
            [EnumMember(Value = "EXTRATO_MOVIMENTO_P")]
            EXTRATOMOVIMENTOPEnum = 15,
            /// <summary>
            /// Enum EXTRATOMOVIMENTOEEnum for EXTRATO_MOVIMENTO_E
            /// </summary>
            [EnumMember(Value = "EXTRATO_MOVIMENTO_E")]
            EXTRATOMOVIMENTOEEnum = 16,
            /// <summary>
            /// Enum EXTRATOMOVIMENTOCEnum for EXTRATO_MOVIMENTO_C
            /// </summary>
            [EnumMember(Value = "EXTRATO_MOVIMENTO_C")]
            EXTRATOMOVIMENTOCEnum = 17,
            /// <summary>
            /// Enum MICROFILMEEnum for MICROFILME
            /// </summary>
            [EnumMember(Value = "MICROFILME")]
            MICROFILMEEnum = 18,
            /// <summary>
            /// Enum DOCPESSOALEnum for DOC_PESSOAL
            /// </summary>
            [EnumMember(Value = "DOC_PESSOAL")]
            DOCPESSOALEnum = 19,
            /// <summary>
            /// Enum DOCELETRONICOEnum for DOCELETRONICO
            /// </summary>
            [EnumMember(Value = "DOCELETRONICO")]
            DOCELETRONICOEnum = 20,
            /// <summary>
            /// Enum DOCINTERNETEnum for DOC_INTERNET
            /// </summary>
            [EnumMember(Value = "DOC_INTERNET")]
            DOCINTERNETEnum = 21,
            /// <summary>
            /// Enum TEDPESSOALEnum for TED_PESSOAL
            /// </summary>
            [EnumMember(Value = "TED_PESSOAL")]
            TEDPESSOALEnum = 22,
            /// <summary>
            /// Enum TEDELETRONICOEnum for TED_ELETRONICO
            /// </summary>
            [EnumMember(Value = "TED_ELETRONICO")]
            TEDELETRONICOEnum = 23,
            /// <summary>
            /// Enum TEDINTERNETEnum for TED_INTERNET
            /// </summary>
            [EnumMember(Value = "TED_INTERNET")]
            TEDINTERNETEnum = 24,
            /// <summary>
            /// Enum DOCTEDAGENDADOPEnum for DOC_TED_AGENDADO_P
            /// </summary>
            [EnumMember(Value = "DOC_TED_AGENDADO_P")]
            DOCTEDAGENDADOPEnum = 25,
            /// <summary>
            /// Enum DOCTEDAGENDADOEEnum for DOC_TED_AGENDADO_E
            /// </summary>
            [EnumMember(Value = "DOC_TED_AGENDADO_E")]
            DOCTEDAGENDADOEEnum = 26,
            /// <summary>
            /// Enum DOCTEDAGENDADOIEnum for DOC_TED_AGENDADO_I
            /// </summary>
            [EnumMember(Value = "DOC_TED_AGENDADO_I")]
            DOCTEDAGENDADOIEnum = 27,
            /// <summary>
            /// Enum TRANSFRECURSOPEnum for TRANSF_RECURSO_P
            /// </summary>
            [EnumMember(Value = "TRANSF_RECURSO_P")]
            TRANSFRECURSOPEnum = 28,
            /// <summary>
            /// Enum TRANSFRECURSOEEnum for TRANSF_RECURSO_E
            /// </summary>
            [EnumMember(Value = "TRANSF_RECURSO_E")]
            TRANSFRECURSOEEnum = 29,
            /// <summary>
            /// Enum ORDEMPAGAMENTOEnum for ORDEM_PAGAMENTO
            /// </summary>
            [EnumMember(Value = "ORDEM_PAGAMENTO")]
            ORDEMPAGAMENTOEnum = 30        }
}
