/*
 * API's OpenData do Open Banking Brasil
 *
 * As API's descritas neste documento são referentes as API's da fase OpenData do Open Banking Brasil.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: apiteam@swagger.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace BGB.OpenBanking.Api.Areas.Common.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class BusinessUnarrangedAccountOverdraft : IEquatable<BusinessUnarrangedAccountOverdraft>
    { 
        /// <summary>
        /// Gets or Sets Fees
        /// </summary>
        [Required]
        [DataMember(Name="fees")]
        public BusinessUnarrangedAccountOverdraftFee Fees { get; set; }

        /// <summary>
        /// Gets or Sets InterestRate
        /// </summary>
        [Required]
        [DataMember(Name="interestRate")]
        public UnarrangedAccountOverdraftRate InterestRate { get; set; }

        /// <summary>
        /// Campo aberto para informar as condições contratuais relativas à Modalidade de Adiantamento a depositante para pessoa natural. Pode ser informada a URL referente ao endereço onde constam as condições informadas. Endereço eletrônico de acesso ao canal.
        /// </summary>
        /// <value>Campo aberto para informar as condições contratuais relativas à Modalidade de Adiantamento a depositante para pessoa natural. Pode ser informada a URL referente ao endereço onde constam as condições informadas. Endereço eletrônico de acesso ao canal.</value>
        [Required]
        [DataMember(Name="termsConditions")]
        public string TermsConditions { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BusinessUnarrangedAccountOverdraft {\n");
            sb.Append("  Fees: ").Append(Fees).Append("\n");
            sb.Append("  InterestRate: ").Append(InterestRate).Append("\n");
            sb.Append("  TermsConditions: ").Append(TermsConditions).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((BusinessUnarrangedAccountOverdraft)obj);
        }

        /// <summary>
        /// Returns true if BusinessUnarrangedAccountOverdraft instances are equal
        /// </summary>
        /// <param name="other">Instance of BusinessUnarrangedAccountOverdraft to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BusinessUnarrangedAccountOverdraft other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Fees == other.Fees ||
                    Fees != null &&
                    Fees.Equals(other.Fees)
                ) && 
                (
                    InterestRate == other.InterestRate ||
                    InterestRate != null &&
                    InterestRate.Equals(other.InterestRate)
                ) && 
                (
                    TermsConditions == other.TermsConditions ||
                    TermsConditions != null &&
                    TermsConditions.Equals(other.TermsConditions)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Fees != null)
                    hashCode = hashCode * 59 + Fees.GetHashCode();
                    if (InterestRate != null)
                    hashCode = hashCode * 59 + InterestRate.GetHashCode();
                    if (TermsConditions != null)
                    hashCode = hashCode * 59 + TermsConditions.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(BusinessUnarrangedAccountOverdraft left, BusinessUnarrangedAccountOverdraft right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(BusinessUnarrangedAccountOverdraft left, BusinessUnarrangedAccountOverdraft right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
