/*
 * API's OpenData do Open Banking Brasil
 *
 * As API's descritas neste documento são referentes as API's da fase OpenData do Open Banking Brasil.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: apiteam@swagger.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace BGB.OpenBanking.Api.Areas.Common.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class CreditCardRewardsProgram : IEquatable<CreditCardRewardsProgram>
    { 
        /// <summary>
        /// Indicador da existência de programa de fidelidade/recompensa associado à conta de pagamento pós-paga (cartão) true false
        /// </summary>
        /// <value>Indicador da existência de programa de fidelidade/recompensa associado à conta de pagamento pós-paga (cartão) true false</value>
        [Required]
        [DataMember(Name="hasRewardProgram")]
        public bool? HasRewardProgram { get; set; }

        /// <summary>
        /// Informações de termos e condições do programa de fidelidade/recompensa. Pode ser informada a URL referente ao endereço onde constam as condições informadas. Será de preenchimento obrigatório caso o campo hasRewardProgram esteja preenchido como true
        /// </summary>
        /// <value>Informações de termos e condições do programa de fidelidade/recompensa. Pode ser informada a URL referente ao endereço onde constam as condições informadas. Será de preenchimento obrigatório caso o campo hasRewardProgram esteja preenchido como true</value>
        [DataMember(Name="rewardProgramInfo")]
        public string RewardProgramInfo { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CreditCardRewardsProgram {\n");
            sb.Append("  HasRewardProgram: ").Append(HasRewardProgram).Append("\n");
            sb.Append("  RewardProgramInfo: ").Append(RewardProgramInfo).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((CreditCardRewardsProgram)obj);
        }

        /// <summary>
        /// Returns true if CreditCardRewardsProgram instances are equal
        /// </summary>
        /// <param name="other">Instance of CreditCardRewardsProgram to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreditCardRewardsProgram other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    HasRewardProgram == other.HasRewardProgram ||
                    HasRewardProgram != null &&
                    HasRewardProgram.Equals(other.HasRewardProgram)
                ) && 
                (
                    RewardProgramInfo == other.RewardProgramInfo ||
                    RewardProgramInfo != null &&
                    RewardProgramInfo.Equals(other.RewardProgramInfo)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (HasRewardProgram != null)
                    hashCode = hashCode * 59 + HasRewardProgram.GetHashCode();
                    if (RewardProgramInfo != null)
                    hashCode = hashCode * 59 + RewardProgramInfo.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(CreditCardRewardsProgram left, CreditCardRewardsProgram right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(CreditCardRewardsProgram left, CreditCardRewardsProgram right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
