/*
 * API's OpenData do Open Banking Brasil
 *
 * As API's descritas neste documento são referentes as API's da fase OpenData do Open Banking Brasil.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: apiteam@swagger.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace BGB.OpenBanking.Api.Areas.Common.Models
{ 
    /// <summary>
    /// Informações sobre taxas de juros
    /// </summary>
    [DataContract]
    public partial class CreditCardInterest : IEquatable<CreditCardInterest>
    { 
        /// <summary>
        /// Gets or Sets FeeRate
        /// </summary>
        [Required]
        [DataMember(Name="feeRate")]
        public InterestRate FeeRate { get; set; }

        /// <summary>
        /// Gets or Sets InstalmentRate
        /// </summary>
        [Required]
        [DataMember(Name="instalmentRate")]
        public InterestRate InstalmentRate { get; set; }

        /// <summary>
        /// Lista de outras operações de crédito
        /// </summary>
        /// <value>Lista de outras operações de crédito</value>
        [Required]
        [DataMember(Name="interestRates")]
        public List<CreditCardInterestRate> InterestRates { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CreditCardInterest {\n");
            sb.Append("  FeeRate: ").Append(FeeRate).Append("\n");
            sb.Append("  InstalmentRate: ").Append(InstalmentRate).Append("\n");
            sb.Append("  InterestRates: ").Append(InterestRates).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((CreditCardInterest)obj);
        }

        /// <summary>
        /// Returns true if CreditCardInterest instances are equal
        /// </summary>
        /// <param name="other">Instance of CreditCardInterest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreditCardInterest other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    FeeRate == other.FeeRate ||
                    FeeRate != null &&
                    FeeRate.Equals(other.FeeRate)
                ) && 
                (
                    InstalmentRate == other.InstalmentRate ||
                    InstalmentRate != null &&
                    InstalmentRate.Equals(other.InstalmentRate)
                ) && 
                (
                    InterestRates == other.InterestRates ||
                    InterestRates != null &&
                    InterestRates.SequenceEqual(other.InterestRates)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (FeeRate != null)
                    hashCode = hashCode * 59 + FeeRate.GetHashCode();
                    if (InstalmentRate != null)
                    hashCode = hashCode * 59 + InstalmentRate.GetHashCode();
                    if (InterestRates != null)
                    hashCode = hashCode * 59 + InterestRates.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(CreditCardInterest left, CreditCardInterest right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(CreditCardInterest left, CreditCardInterest right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
