/*
 * API's OpenData do Open Banking Brasil
 *
 * As API's descritas neste documento são referentes as API's da fase OpenData do Open Banking Brasil.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: apiteam@swagger.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace BGB.OpenBanking.Api.Areas.Common.Models
{ 
        /// <summary>
        /// Relação de garantias exigidas, segundo documento 3040 do Bacen: * `cessão de direitos creditórios`: o cedente transfere ao credor/cessionário a titularidade de direitos creditórios, até a liquidação da dívida. O credor/cessionário passa a recebê-los diretamente dos devedores e credita o produto da operação para o cedente na operação que originou a cessão, até a sua liquidação * `caução`: garantia instituída sobre créditos do garantidor * `penhor`: direito real que consiste na tradição de uma coisa móvel ou mobilizável, suscetível de alienação, realizada pelo devedor ou por terceiro ao credor, a fim de garantir o pagamento do débito * `alienação fiduciária`: transferência ao credor, ou fiduciário, da propriedade do bem * `hipoteca`: direito real de garantia que afeta um bem imóvel para o cumprimento da obrigação * `operações garantidas pelo governo`: nas instâncias federal, estadual ou municipal * `outras garantias não fidejussórias`: as garantias reais não descritas como: cessão de direitos creditórios, caução, penhor, alienação fiduciária, hipoteca ou operação garantida pelo governo * `seguros e assemelhados`: os seguros (e assemelhados) contratados para garantir o pagamento da operação em circunstâncias adversas * `garantia fidejussória`: baseada na fidelidade do garantidor em cumprir as obrigações, caso o devedor não o faça * `bens arrendados`: bem objeto do arrendamento financeiro * `garantias internacionais`: declarar se a garantia é mitigadora ou não, observados os critérios definidos pela Circular 3.644, de 4 de março de 2013 * `operações garantidas por outras entidade`: declarar as garantias prestadas pelas entidades descritas no item 3. Informações de Garantias (i) do documento 3040 - Bacen * `acordos de compensação`: operações que sejam abrangidas por acordos para a compensação e liquidação de obrigações no âmbito do SFN, nos termos da Resolução 3.263, de 24 de fevereiro de 2005 * `não aplicável` 
        /// </summary>
        /// <value>Relação de garantias exigidas, segundo documento 3040 do Bacen: * `cessão de direitos creditórios`: o cedente transfere ao credor/cessionário a titularidade de direitos creditórios, até a liquidação da dívida. O credor/cessionário passa a recebê-los diretamente dos devedores e credita o produto da operação para o cedente na operação que originou a cessão, até a sua liquidação * `caução`: garantia instituída sobre créditos do garantidor * `penhor`: direito real que consiste na tradição de uma coisa móvel ou mobilizável, suscetível de alienação, realizada pelo devedor ou por terceiro ao credor, a fim de garantir o pagamento do débito * `alienação fiduciária`: transferência ao credor, ou fiduciário, da propriedade do bem * `hipoteca`: direito real de garantia que afeta um bem imóvel para o cumprimento da obrigação * `operações garantidas pelo governo`: nas instâncias federal, estadual ou municipal * `outras garantias não fidejussórias`: as garantias reais não descritas como: cessão de direitos creditórios, caução, penhor, alienação fiduciária, hipoteca ou operação garantida pelo governo * `seguros e assemelhados`: os seguros (e assemelhados) contratados para garantir o pagamento da operação em circunstâncias adversas * `garantia fidejussória`: baseada na fidelidade do garantidor em cumprir as obrigações, caso o devedor não o faça * `bens arrendados`: bem objeto do arrendamento financeiro * `garantias internacionais`: declarar se a garantia é mitigadora ou não, observados os critérios definidos pela Circular 3.644, de 4 de março de 2013 * `operações garantidas por outras entidade`: declarar as garantias prestadas pelas entidades descritas no item 3. Informações de Garantias (i) do documento 3040 - Bacen * `acordos de compensação`: operações que sejam abrangidas por acordos para a compensação e liquidação de obrigações no âmbito do SFN, nos termos da Resolução 3.263, de 24 de fevereiro de 2005 * `não aplicável` </value>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum RequiredWarranty
        {
            /// <summary>
            /// Enum CESSAODIREITOSCREDITORIOSEnum for CESSAO_DIREITOS_CREDITORIOS
            /// </summary>
            [EnumMember(Value = "CESSAO_DIREITOS_CREDITORIOS")]
            CESSAODIREITOSCREDITORIOSEnum = 0,
            /// <summary>
            /// Enum CAUCAOEnum for CAUCAO
            /// </summary>
            [EnumMember(Value = "CAUCAO")]
            CAUCAOEnum = 1,
            /// <summary>
            /// Enum PENHOREnum for PENHOR
            /// </summary>
            [EnumMember(Value = "PENHOR")]
            PENHOREnum = 2,
            /// <summary>
            /// Enum ALIENACAOFIDUCIARIAEnum for ALIENACAO_FIDUCIARIA
            /// </summary>
            [EnumMember(Value = "ALIENACAO_FIDUCIARIA")]
            ALIENACAOFIDUCIARIAEnum = 3,
            /// <summary>
            /// Enum HIPOTECAEnum for HIPOTECA
            /// </summary>
            [EnumMember(Value = "HIPOTECA")]
            HIPOTECAEnum = 4,
            /// <summary>
            /// Enum OPERACOESGARANTIDASPELOGOVERNOEnum for OPERACOES_GARANTIDAS_PELO_GOVERNO
            /// </summary>
            [EnumMember(Value = "OPERACOES_GARANTIDAS_PELO_GOVERNO")]
            OPERACOESGARANTIDASPELOGOVERNOEnum = 5,
            /// <summary>
            /// Enum OUTRASGARANTIASNAOFIDEJUSSORIASEnum for OUTRAS_GARANTIAS_NAO_FIDEJUSSORIAS
            /// </summary>
            [EnumMember(Value = "OUTRAS_GARANTIAS_NAO_FIDEJUSSORIAS")]
            OUTRASGARANTIASNAOFIDEJUSSORIASEnum = 6,
            /// <summary>
            /// Enum SEGUROSASSEMELHADOSEnum for SEGUROS_ASSEMELHADOS
            /// </summary>
            [EnumMember(Value = "SEGUROS_ASSEMELHADOS")]
            SEGUROSASSEMELHADOSEnum = 7,
            /// <summary>
            /// Enum GARANTIAFIDEJUSSORIAEnum for GARANTIA_FIDEJUSSORIA
            /// </summary>
            [EnumMember(Value = "GARANTIA_FIDEJUSSORIA")]
            GARANTIAFIDEJUSSORIAEnum = 8,
            /// <summary>
            /// Enum BENSARRENDADOSEnum for BENS_ARRENDADOS
            /// </summary>
            [EnumMember(Value = "BENS_ARRENDADOS")]
            BENSARRENDADOSEnum = 9,
            /// <summary>
            /// Enum GARANTIASINTERNACIONAISEnum for GARANTIAS_INTERNACIONAIS
            /// </summary>
            [EnumMember(Value = "GARANTIAS_INTERNACIONAIS")]
            GARANTIASINTERNACIONAISEnum = 10,
            /// <summary>
            /// Enum OPERACOESGARANTIDASOUTRASENTIDADESEnum for OPERACOES_GARANTIDAS_OUTRAS_ENTIDADES
            /// </summary>
            [EnumMember(Value = "OPERACOES_GARANTIDAS_OUTRAS_ENTIDADES")]
            OPERACOESGARANTIDASOUTRASENTIDADESEnum = 11,
            /// <summary>
            /// Enum ACORDOSCOMPENSACAOEnum for ACORDOS_COMPENSACAO
            /// </summary>
            [EnumMember(Value = "ACORDOS_COMPENSACAO")]
            ACORDOSCOMPENSACAOEnum = 12,
            /// <summary>
            /// Enum NAOAPLICAVELEnum for NAO_APLICAVEL
            /// </summary>
            [EnumMember(Value = "NAO_APLICAVEL")]
            NAOAPLICAVELEnum = 13        }
}
