/*
 * API's OpenData do Open Banking Brasil
 *
 * As API's descritas neste documento são referentes as API's da fase OpenData do Open Banking Brasil.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: apiteam@swagger.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;

namespace BGB.OpenBanking.Api.Contracts.Common
{
    /// <summary>
    ///
    /// </summary>
    [DataContract]
    public partial class BusinessInvoiceFinancings : IEquatable<BusinessInvoiceFinancings>
    {
        /// <summary>
        /// Modalidades de direitos creditórios descontados ofertados para pessoas Jurídicas, conforme Circular 4015-Bacen. Direito creditório descontado é a antecipação de créditos relativos por ex. ao: desconto de duplicatas, desconto de cheques,antecipação de fatura de cartão de crédito
        /// </summary>
        /// <value>Modalidades de direitos creditórios descontados ofertados para pessoas Jurídicas, conforme Circular 4015-Bacen. Direito creditório descontado é a antecipação de créditos relativos por ex. ao: desconto de duplicatas, desconto de cheques,antecipação de fatura de cartão de crédito</value>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum TypeEnum
        {
            /// <summary>
            /// Enum DESCONTODUPLICATASEnum for DESCONTO_DUPLICATAS
            /// </summary>
            [EnumMember(Value = "DESCONTO_DUPLICATAS")]
            DESCONTODUPLICATASEnum = 0,

            /// <summary>
            /// Enum DESCONTOCHEQUESEnum for DESCONTO_CHEQUES
            /// </summary>
            [EnumMember(Value = "DESCONTO_CHEQUES")]
            DESCONTOCHEQUESEnum = 1,

            /// <summary>
            /// Enum ANTECIPACAOFATURACARTAOCREDITOEnum for ANTECIPACAO_FATURA_CARTAO_CREDITO
            /// </summary>
            [EnumMember(Value = "ANTECIPACAO_FATURA_CARTAO_CREDITO")]
            ANTECIPACAOFATURACARTAOCREDITOEnum = 2,

            /// <summary>
            /// Enum OUTROSDIREITOSCREDITORIOSDESCONTADOSEnum for OUTROS_DIREITOS_CREDITORIOS_DESCONTADOS
            /// </summary>
            [EnumMember(Value = "OUTROS_DIREITOS_CREDITORIOS_DESCONTADOS")]
            OUTROSDIREITOSCREDITORIOSDESCONTADOSEnum = 3,

            /// <summary>
            /// Enum OUTROSTITULOSDESCONTADOSEnum for OUTROS_TITULOS_DESCONTADOS
            /// </summary>
            [EnumMember(Value = "OUTROS_TITULOS_DESCONTADOS")]
            OUTROSTITULOSDESCONTADOSEnum = 4
        }

        /// <summary>
        /// Modalidades de direitos creditórios descontados ofertados para pessoas Jurídicas, conforme Circular 4015-Bacen. Direito creditório descontado é a antecipação de créditos relativos por ex. ao: desconto de duplicatas, desconto de cheques,antecipação de fatura de cartão de crédito
        /// </summary>
        /// <value>Modalidades de direitos creditórios descontados ofertados para pessoas Jurídicas, conforme Circular 4015-Bacen. Direito creditório descontado é a antecipação de créditos relativos por ex. ao: desconto de duplicatas, desconto de cheques,antecipação de fatura de cartão de crédito</value>
        [Required]
        [DataMember(Name = "type")]
        public TypeEnum? Type { get; set; }

        /// <summary>
        /// Gets or Sets Fees
        /// </summary>
        [Required]
        [DataMember(Name = "fees")]
        public BusinessInvoiceFinancingsFees Fees { get; set; }

        /// <summary>
        /// Gets or Sets InterestRate
        /// </summary>
        [Required]
        [DataMember(Name = "interestRate")]
        public BusinessInvoiceFinancingsInterestRate InterestRate { get; set; }

        /// <summary>
        /// Lista das  garantias exigidas
        /// </summary>
        /// <value>Lista das  garantias exigidas</value>
        [Required]
        [DataMember(Name = "requiredWarranties")]
        public List<RequiredWarranty> RequiredWarranties { get; set; }

        /// <summary>
        /// Campo aberto para informar as condições contratuais relativas à Modalidade de Financiamentos para pessoa jurídica informada. Pode ser informada a URL referente ao endereço onde constam as condições informadas. Endereço eletrônico de acesso ao canal.
        /// </summary>
        /// <value>Campo aberto para informar as condições contratuais relativas à Modalidade de Financiamentos para pessoa jurídica informada. Pode ser informada a URL referente ao endereço onde constam as condições informadas. Endereço eletrônico de acesso ao canal.</value>
        [Required]
        [DataMember(Name = "termsConditions")]
        public string TermsConditions { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BusinessInvoiceFinancings {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Fees: ").Append(Fees).Append("\n");
            sb.Append("  InterestRate: ").Append(InterestRate).Append("\n");
            sb.Append("  RequiredWarranties: ").Append(RequiredWarranties).Append("\n");
            sb.Append("  TermsConditions: ").Append(TermsConditions).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((BusinessInvoiceFinancings)obj);
        }

        /// <summary>
        /// Returns true if BusinessInvoiceFinancings instances are equal
        /// </summary>
        /// <param name="other">Instance of BusinessInvoiceFinancings to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BusinessInvoiceFinancings other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    Type == other.Type ||
                    Type != null &&
                    Type.Equals(other.Type)
                ) &&
                (
                    Fees == other.Fees ||
                    Fees != null &&
                    Fees.Equals(other.Fees)
                ) &&
                (
                    InterestRate == other.InterestRate ||
                    InterestRate != null &&
                    InterestRate.Equals(other.InterestRate)
                ) &&
                (
                    RequiredWarranties == other.RequiredWarranties ||
                    RequiredWarranties != null &&
                    RequiredWarranties.SequenceEqual(other.RequiredWarranties)
                ) &&
                (
                    TermsConditions == other.TermsConditions ||
                    TermsConditions != null &&
                    TermsConditions.Equals(other.TermsConditions)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (Type != null)
                    hashCode = hashCode * 59 + Type.GetHashCode();
                if (Fees != null)
                    hashCode = hashCode * 59 + Fees.GetHashCode();
                if (InterestRate != null)
                    hashCode = hashCode * 59 + InterestRate.GetHashCode();
                if (RequiredWarranties != null)
                    hashCode = hashCode * 59 + RequiredWarranties.GetHashCode();
                if (TermsConditions != null)
                    hashCode = hashCode * 59 + TermsConditions.GetHashCode();
                return hashCode;
            }
        }

        #region Operators

#pragma warning disable 1591

        public static bool operator ==(BusinessInvoiceFinancings left, BusinessInvoiceFinancings right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(BusinessInvoiceFinancings left, BusinessInvoiceFinancings right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591

        #endregion Operators
    }
}