/*
 * API's OpenData do Open Banking Brasil
 *
 * As API's descritas neste documento são referentes as API's da fase OpenData do Open Banking Brasil.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: apiteam@swagger.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using Newtonsoft.Json;
using System;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;

namespace BGB.OpenBanking.Api.Contracts.Common
{
    /// <summary>
    ///
    /// </summary>
    [DataContract]
    public partial class CreditCardIdentification : IEquatable<CreditCardIdentification>
    {
        /// <summary>
        /// Gets or Sets Product
        /// </summary>
        [Required]
        [DataMember(Name = "product")]
        public CreditCardIdentificationProduct Product { get; set; }

        /// <summary>
        /// Gets or Sets CreditCard
        /// </summary>
        [Required]
        [DataMember(Name = "creditCard")]
        public CreditCardIdentificationCreditCard CreditCard { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CreditCardIdentification {\n");
            sb.Append("  Product: ").Append(Product).Append("\n");
            sb.Append("  CreditCard: ").Append(CreditCard).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((CreditCardIdentification)obj);
        }

        /// <summary>
        /// Returns true if CreditCardIdentification instances are equal
        /// </summary>
        /// <param name="other">Instance of CreditCardIdentification to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreditCardIdentification other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    Product == other.Product ||
                    Product != null &&
                    Product.Equals(other.Product)
                ) &&
                (
                    CreditCard == other.CreditCard ||
                    CreditCard != null &&
                    CreditCard.Equals(other.CreditCard)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (Product != null)
                    hashCode = hashCode * 59 + Product.GetHashCode();
                if (CreditCard != null)
                    hashCode = hashCode * 59 + CreditCard.GetHashCode();
                return hashCode;
            }
        }

        #region Operators

#pragma warning disable 1591

        public static bool operator ==(CreditCardIdentification left, CreditCardIdentification right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(CreditCardIdentification left, CreditCardIdentification right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591

        #endregion Operators
    }
}