/*
 * API's OpenData do Open Banking Brasil
 *
 * As API's descritas neste documento são referentes as API's da fase OpenData do Open Banking Brasil.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: apiteam@swagger.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace BGB.OpenBanking.Api.Contracts.Common
{
    /// <summary>
    /// Tipos de taxas referenciais ou indexadores, conforme Anexo 5: Taxa referencial ou Indexador (Indx), do Documento 3040
    /// </summary>
    /// <value>Tipos de taxas referenciais ou indexadores, conforme Anexo 5: Taxa referencial ou Indexador (Indx), do Documento 3040 </value>
    [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
    public enum ReferentialRateIndexer
    {
        /// <summary>
        /// Enum SEMINDEXADORTAXAEnum for SEM_INDEXADOR_TAXA
        /// </summary>
        [EnumMember(Value = "SEM_INDEXADOR_TAXA")]
        SEMINDEXADORTAXAEnum = 0,

        /// <summary>
        /// Enum PREFIXADOEnum for PRE_FIXADO
        /// </summary>
        [EnumMember(Value = "PRE_FIXADO")]
        PREFIXADOEnum = 1,

        /// <summary>
        /// Enum POSFIXADOTRTBFEnum for POS_FIXADO_TR_TBF
        /// </summary>
        [EnumMember(Value = "POS_FIXADO_TR_TBF")]
        POSFIXADOTRTBFEnum = 2,

        /// <summary>
        /// Enum POSFIXADOTJLPEnum for POS_FIXADO_TJLP
        /// </summary>
        [EnumMember(Value = "POS_FIXADO_TJLP")]
        POSFIXADOTJLPEnum = 3,

        /// <summary>
        /// Enum POSFIXADOLIBOREnum for POS_FIXADO_LIBOR
        /// </summary>
        [EnumMember(Value = "POS_FIXADO_LIBOR")]
        POSFIXADOLIBOREnum = 4,

        /// <summary>
        /// Enum POSFIXADOTLPEnum for POS_FIXADO_TLP
        /// </summary>
        [EnumMember(Value = "POS_FIXADO_TLP")]
        POSFIXADOTLPEnum = 5,

        /// <summary>
        /// Enum OUTRASTAXASPOSFIXADASEnum for OUTRAS_TAXAS_POS_FIXADAS
        /// </summary>
        [EnumMember(Value = "OUTRAS_TAXAS_POS_FIXADAS")]
        OUTRASTAXASPOSFIXADASEnum = 6,

        /// <summary>
        /// Enum FLUTUANTESCDIEnum for FLUTUANTES_CDI
        /// </summary>
        [EnumMember(Value = "FLUTUANTES_CDI")]
        FLUTUANTESCDIEnum = 7,

        /// <summary>
        /// Enum FLUTUANTESSELICEnum for FLUTUANTES_SELIC
        /// </summary>
        [EnumMember(Value = "FLUTUANTES_SELIC")]
        FLUTUANTESSELICEnum = 8,

        /// <summary>
        /// Enum OUTRASTAXASFLUTUANTESEnum for OUTRAS_TAXAS_FLUTUANTES
        /// </summary>
        [EnumMember(Value = "OUTRAS_TAXAS_FLUTUANTES")]
        OUTRASTAXASFLUTUANTESEnum = 9,

        /// <summary>
        /// Enum INDICESPRECOSIGPMEnum for INDICES_PRECOS_IGPM
        /// </summary>
        [EnumMember(Value = "INDICES_PRECOS_IGPM")]
        INDICESPRECOSIGPMEnum = 10,

        /// <summary>
        /// Enum INDICESPRECOSIPCAEnum for INDICES_PRECOS_IPCA
        /// </summary>
        [EnumMember(Value = "INDICES_PRECOS_IPCA")]
        INDICESPRECOSIPCAEnum = 11,

        /// <summary>
        /// Enum INDICESPRECOSIPCCEnum for INDICES_PRECOS_IPCC
        /// </summary>
        [EnumMember(Value = "INDICES_PRECOS_IPCC")]
        INDICESPRECOSIPCCEnum = 12,

        /// <summary>
        /// Enum OUTROSINDICESPRECOEnum for OUTROS_INDICES_PRECO
        /// </summary>
        [EnumMember(Value = "OUTROS_INDICES_PRECO")]
        OUTROSINDICESPRECOEnum = 13,

        /// <summary>
        /// Enum CREDITORURALTCRPREEnum for CREDITO_RURAL_TCR_PRE
        /// </summary>
        [EnumMember(Value = "CREDITO_RURAL_TCR_PRE")]
        CREDITORURALTCRPREEnum = 14,

        /// <summary>
        /// Enum CREDITORURALTCRPOSEnum for CREDITO_RURAL_TCR_POS
        /// </summary>
        [EnumMember(Value = "CREDITO_RURAL_TCR_POS")]
        CREDITORURALTCRPOSEnum = 15,

        /// <summary>
        /// Enum CREDITORURALTRFCPREEnum for CREDITO_RURAL_TRFC_PRE
        /// </summary>
        [EnumMember(Value = "CREDITO_RURAL_TRFC_PRE")]
        CREDITORURALTRFCPREEnum = 16,

        /// <summary>
        /// Enum CREDITORURALTRFCPOSEnum for CREDITO_RURAL_TRFC_POS
        /// </summary>
        [EnumMember(Value = "CREDITO_RURAL_TRFC_POS")]
        CREDITORURALTRFCPOSEnum = 17,

        /// <summary>
        /// Enum OUTROSINDEXADORESEnum for OUTROS_INDEXADORES
        /// </summary>
        [EnumMember(Value = "OUTROS_INDEXADORES")]
        OUTROSINDEXADORESEnum = 18
    }
}