/*
 * APIs OpenData do Open Banking Brasil
 *
 * As APIs descritas neste documento são referentes as APIs da fase OpenData do Open Banking Brasil.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: apiteam@swagger.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;

namespace BGB.OpenBanking.Api.Contracts.Products_Services
{
    /// <summary>
    ///
    /// </summary>
    [DataContract]
    public partial class PhoneChannelIdentification : IEquatable<PhoneChannelIdentification>
    {
        /// <summary>
        /// Tipo de canal telefônico de atendimento
        /// </summary>
        /// <value>Tipo de canal telefônico de atendimento</value>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum TypeEnum
        {
            /// <summary>
            /// Enum CENTRALTELEFONICAEnum for CENTRAL_TELEFONICA
            /// </summary>
            [EnumMember(Value = "CENTRAL_TELEFONICA")]
            CENTRALTELEFONICAEnum = 0,

            /// <summary>
            /// Enum SACEnum for SAC
            /// </summary>
            [EnumMember(Value = "SAC")]
            SACEnum = 1,

            /// <summary>
            /// Enum OUVIDORIAEnum for OUVIDORIA
            /// </summary>
            [EnumMember(Value = "OUVIDORIA")]
            OUVIDORIAEnum = 2,

            /// <summary>
            /// Enum OUTROSEnum for OUTROS
            /// </summary>
            [EnumMember(Value = "OUTROS")]
            OUTROSEnum = 3
        }

        /// <summary>
        /// Tipo de canal telefônico de atendimento
        /// </summary>
        /// <value>Tipo de canal telefônico de atendimento</value>
        [Required]
        [DataMember(Name = "type")]
        public TypeEnum? Type { get; set; }

        /// <summary>
        /// Campo de texto livre para descrever quando o tipo de canal de atendimento for Outros
        /// </summary>
        /// <value>Campo de texto livre para descrever quando o tipo de canal de atendimento for Outros</value>
        [DataMember(Name = "additionalInfo")]
        public string AdditionalInfo { get; set; }

        /// <summary>
        /// Lista de telefones do Canal de Atendimento
        /// </summary>
        /// <value>Lista de telefones do Canal de Atendimento</value>
        [DataMember(Name = "phones")]
        public List<PhoneChannelPhone> Phones { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PhoneChannelIdentification {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  AdditionalInfo: ").Append(AdditionalInfo).Append("\n");
            sb.Append("  Phones: ").Append(Phones).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((PhoneChannelIdentification)obj);
        }

        /// <summary>
        /// Returns true if PhoneChannelIdentification instances are equal
        /// </summary>
        /// <param name="other">Instance of PhoneChannelIdentification to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PhoneChannelIdentification other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    Type == other.Type ||
                    Type != null &&
                    Type.Equals(other.Type)
                ) &&
                (
                    AdditionalInfo == other.AdditionalInfo ||
                    AdditionalInfo != null &&
                    AdditionalInfo.Equals(other.AdditionalInfo)
                ) &&
                (
                    Phones == other.Phones ||
                    Phones != null &&
                    Phones.SequenceEqual(other.Phones)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (Type != null)
                    hashCode = hashCode * 59 + Type.GetHashCode();
                if (AdditionalInfo != null)
                    hashCode = hashCode * 59 + AdditionalInfo.GetHashCode();
                if (Phones != null)
                    hashCode = hashCode * 59 + Phones.GetHashCode();
                return hashCode;
            }
        }

        #region Operators

#pragma warning disable 1591

        public static bool operator ==(PhoneChannelIdentification left, PhoneChannelIdentification right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(PhoneChannelIdentification left, PhoneChannelIdentification right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591

        #endregion Operators
    }
}