/*
 * APIs OpenData do Open Banking Brasil
 *
 * As APIs descritas neste documento são referentes as APIs da fase OpenData do Open Banking Brasil.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: apiteam@swagger.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using Newtonsoft.Json;
using System;
using System.Runtime.Serialization;
using System.Text;

namespace BGB.OpenBanking.Api.Contracts.Products_Services
{
    /// <summary>
    ///
    /// </summary>
    [DataContract]
    public partial class SharedAutomatedTellerMachinesServices : IEquatable<SharedAutomatedTellerMachinesServices>
    {
        /// <summary>
        /// Nome dos Serviços efetivamente prestados pelo Terminal de Autoatendimento Compartilhado informado
        /// </summary>
        /// <value>Nome dos Serviços efetivamente prestados pelo Terminal de Autoatendimento Compartilhado informado</value>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum NameEnum
        {
            /// <summary>
            /// Enum ABERTURACONTASDEPOSITOSOUPAGAMENTOPREPAGAEnum for ABERTURA_CONTAS_DEPOSITOS_OU_PAGAMENTO_PRE_PAGA
            /// </summary>
            [EnumMember(Value = "ABERTURA_CONTAS_DEPOSITOS_OU_PAGAMENTO_PRE_PAGA")]
            ABERTURACONTASDEPOSITOSOUPAGAMENTOPREPAGAEnum = 0,

            /// <summary>
            /// Enum SAQUEMOEDAEMESPECIEEnum for SAQUE_MOEDA_EM_ESPECIE
            /// </summary>
            [EnumMember(Value = "SAQUE_MOEDA_EM_ESPECIE")]
            SAQUEMOEDAEMESPECIEEnum = 1,

            /// <summary>
            /// Enum RECEBIMENTOSPAGAMENTOSQUALQUERNATUREZAEnum for RECEBIMENTOS_PAGAMENTOS_QUALQUER_NATUREZA
            /// </summary>
            [EnumMember(Value = "RECEBIMENTOS_PAGAMENTOS_QUALQUER_NATUREZA")]
            RECEBIMENTOSPAGAMENTOSQUALQUERNATUREZAEnum = 2,

            /// <summary>
            /// Enum TRANSFERENCIASELETRONICASVISANDOMOVIMENTACAOEnum for TRANSFERENCIAS_ELETRONICAS_VISANDO_MOVIMENTACAO
            /// </summary>
            [EnumMember(Value = "TRANSFERENCIAS_ELETRONICAS_VISANDO_MOVIMENTACAO")]
            TRANSFERENCIASELETRONICASVISANDOMOVIMENTACAOEnum = 3,

            /// <summary>
            /// Enum CONTASDEPOSITOSOUPAGAMENTOTITULARIDADECLIENTESEnum for CONTAS_DEPOSITOS_OU_PAGAMENTO_TITULARIDADE_CLIENTES
            /// </summary>
            [EnumMember(Value = "CONTAS_DEPOSITOS_OU_PAGAMENTO_TITULARIDADE_CLIENTES")]
            CONTASDEPOSITOSOUPAGAMENTOTITULARIDADECLIENTESEnum = 4,

            /// <summary>
            /// Enum CONSULTASALDOSEXTRATOSCONTASDEPOSITOSECONTASEnum for CONSULTA_SALDOS_EXTRATOS_CONTAS_DEPOSITOS_E_CONTAS
            /// </summary>
            [EnumMember(Value = "CONSULTA_SALDOS_EXTRATOS_CONTAS_DEPOSITOS_E_CONTAS")]
            CONSULTASALDOSEXTRATOSCONTASDEPOSITOSECONTASEnum = 5,

            /// <summary>
            /// Enum PAGAMENTOSEnum for PAGAMENTOS
            /// </summary>
            [EnumMember(Value = "PAGAMENTOS")]
            PAGAMENTOSEnum = 6,

            /// <summary>
            /// Enum APLICACOESRESGATESINVESTIMENTOSEnum for APLICACOES_RESGATES_INVESTIMENTOS
            /// </summary>
            [EnumMember(Value = "APLICACOES_RESGATES_INVESTIMENTOS")]
            APLICACOESRESGATESINVESTIMENTOSEnum = 7,

            /// <summary>
            /// Enum EXECUCAOATIVAPASSIVAORDENSPAGAMENTOSOLICITACAOEnum for EXECUCAO_ATIVA_PASSIVA_ORDENS_PAGAMENTO_SOLICITACAO
            /// </summary>
            [EnumMember(Value = "EXECUCAO_ATIVA_PASSIVA_ORDENS_PAGAMENTO_SOLICITACAO")]
            EXECUCAOATIVAPASSIVAORDENSPAGAMENTOSOLICITACAOEnum = 8,

            /// <summary>
            /// Enum CLIENTESUSUARIOSEnum for CLIENTES_USUARIOS
            /// </summary>
            [EnumMember(Value = "CLIENTES_USUARIOS")]
            CLIENTESUSUARIOSEnum = 9,

            /// <summary>
            /// Enum DEPOSITOSMOEDAESPECIECHEQUEEnum for DEPOSITOS_MOEDA_ESPECIE_CHEQUE
            /// </summary>
            [EnumMember(Value = "DEPOSITOS_MOEDA_ESPECIE_CHEQUE")]
            DEPOSITOSMOEDAESPECIECHEQUEEnum = 10,

            /// <summary>
            /// Enum OPERACOESCREDITOBEMCOMOOUTROSSERVICOSPRESTADOSACOMPANHAMENTOOPERACAOEnum for OPERACOES_CREDITO_BEM_COMO_OUTROS_SERVICOS_PRESTADOS_ACOMPANHAMENTO_OPERACAO
            /// </summary>
            [EnumMember(Value = "OPERACOES_CREDITO_BEM_COMO_OUTROS_SERVICOS_PRESTADOS_ACOMPANHAMENTO_OPERACAO")]
            OPERACOESCREDITOBEMCOMOOUTROSSERVICOSPRESTADOSACOMPANHAMENTOOPERACAOEnum = 11,

            /// <summary>
            /// Enum CARTAOCREDITOEnum for CARTAO_CREDITO
            /// </summary>
            [EnumMember(Value = "CARTAO_CREDITO")]
            CARTAOCREDITOEnum = 12,

            /// <summary>
            /// Enum SEGUROSEnum for SEGUROS
            /// </summary>
            [EnumMember(Value = "SEGUROS")]
            SEGUROSEnum = 13,

            /// <summary>
            /// Enum OPERACOESARRENDAMENTOMERCANTILEnum for OPERACOES_ARRENDAMENTO_MERCANTIL
            /// </summary>
            [EnumMember(Value = "OPERACOES_ARRENDAMENTO_MERCANTIL")]
            OPERACOESARRENDAMENTOMERCANTILEnum = 14,

            /// <summary>
            /// Enum ABERTURACONTAPAGAMENTOPOSPAGAEnum for ABERTURA_CONTA_PAGAMENTO_POS_PAGA
            /// </summary>
            [EnumMember(Value = "ABERTURA_CONTA_PAGAMENTO_POS_PAGA")]
            ABERTURACONTAPAGAMENTOPOSPAGAEnum = 15,

            /// <summary>
            /// Enum COMPRAVENDAMOEDAESTRANGEIRAESPECIEEnum for COMPRA_VENDA_MOEDA_ESTRANGEIRA_ESPECIE
            /// </summary>
            [EnumMember(Value = "COMPRA_VENDA_MOEDA_ESTRANGEIRA_ESPECIE")]
            COMPRAVENDAMOEDAESTRANGEIRAESPECIEEnum = 16,

            /// <summary>
            /// Enum COMPRAVENDACHEQUECHEQUEVIAGEMBEMCOMOCARGAMOEDAESTRANGEIRACARTAOPREPAGOEnum for COMPRA_VENDA_CHEQUE_CHEQUE_VIAGEM_BEM_COMO_CARGA_MOEDA_ESTRANGEIRA_CARTAO_PRE_PAGO
            /// </summary>
            [EnumMember(Value = "COMPRA_VENDA_CHEQUE_CHEQUE_VIAGEM_BEM_COMO_CARGA_MOEDA_ESTRANGEIRA_CARTAO_PRE_PAGO")]
            COMPRAVENDACHEQUECHEQUEVIAGEMBEMCOMOCARGAMOEDAESTRANGEIRACARTAOPREPAGOEnum = 17,

            /// <summary>
            /// Enum COMPRAVENDAOUROEnum for COMPRA_VENDA_OURO
            /// </summary>
            [EnumMember(Value = "COMPRA_VENDA_OURO")]
            COMPRAVENDAOUROEnum = 18,

            /// <summary>
            /// Enum OUTROSPRODUTOSSERVICOSEnum for OUTROS_PRODUTOS_SERVICOS
            /// </summary>
            [EnumMember(Value = "OUTROS_PRODUTOS_SERVICOS")]
            OUTROSPRODUTOSSERVICOSEnum = 19,

            /// <summary>
            /// Enum CANCELAMENTOEnum for CANCELAMENTO
            /// </summary>
            [EnumMember(Value = "CANCELAMENTO")]
            CANCELAMENTOEnum = 20,

            /// <summary>
            /// Enum INFORMACOESEnum for INFORMACOES
            /// </summary>
            [EnumMember(Value = "INFORMACOES")]
            INFORMACOESEnum = 21,

            /// <summary>
            /// Enum RECLAMACOESEnum for RECLAMACOES
            /// </summary>
            [EnumMember(Value = "RECLAMACOES")]
            RECLAMACOESEnum = 22
        }

        /// <summary>
        /// Nome dos Serviços efetivamente prestados pelo Terminal de Autoatendimento Compartilhado informado
        /// </summary>
        /// <value>Nome dos Serviços efetivamente prestados pelo Terminal de Autoatendimento Compartilhado informado</value>
        [DataMember(Name = "name")]
        public NameEnum? Name { get; set; }

        /// <summary>
        /// Código dos Serviços efetivamente prestados pelo Terminal de Autoatendimento Compartilhado informado
        /// </summary>
        /// <value>Código dos Serviços efetivamente prestados pelo Terminal de Autoatendimento Compartilhado informado</value>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum CodeEnum
        {
            /// <summary>
            /// Enum ABRECONTADEPOSITOOUPREPAGAEnum for ABRE_CONTA_DEPOSITO_OU_PRE_PAGA
            /// </summary>
            [EnumMember(Value = "ABRE_CONTA_DEPOSITO_OU_PRE_PAGA")]
            ABRECONTADEPOSITOOUPREPAGAEnum = 0,

            /// <summary>
            /// Enum SAQUEMOEDAESPECIEEnum for SAQUE_MOEDA_ESPECIE
            /// </summary>
            [EnumMember(Value = "SAQUE_MOEDA_ESPECIE")]
            SAQUEMOEDAESPECIEEnum = 1,

            /// <summary>
            /// Enum RECEBEPAGAQUALQUERNATUREZAEnum for RECEBE_PAGA_QUALQUER_NATUREZA
            /// </summary>
            [EnumMember(Value = "RECEBE_PAGA_QUALQUER_NATUREZA")]
            RECEBEPAGAQUALQUERNATUREZAEnum = 2,

            /// <summary>
            /// Enum TRANSFERENCIASELETRONICASMOVIMENTACONTASDEPOSITOSOUPAGATITULARESCLIENTESEnum for TRANSFERENCIAS_ELETRONICAS_MOVIMENTA_CONTAS_DEPOSITOS_OU_PAGA_TITULARES_CLIENTES
            /// </summary>
            [EnumMember(Value = "TRANSFERENCIAS_ELETRONICAS_MOVIMENTA_CONTAS_DEPOSITOS_OU_PAGA_TITULARES_CLIENTES")]
            TRANSFERENCIASELETRONICASMOVIMENTACONTASDEPOSITOSOUPAGATITULARESCLIENTESEnum = 3,

            /// <summary>
            /// Enum CONSULTASALDOSEXTRATOSCONTASDEPOSITOSEnum for CONSULTA_SALDOS_EXTRATOS_CONTAS_DEPOSITOS
            /// </summary>
            [EnumMember(Value = "CONSULTA_SALDOS_EXTRATOS_CONTAS_DEPOSITOS")]
            CONSULTASALDOSEXTRATOSCONTASDEPOSITOSEnum = 4,

            /// <summary>
            /// Enum PAGAMENTOSEnum for PAGAMENTOS
            /// </summary>
            [EnumMember(Value = "PAGAMENTOS")]
            PAGAMENTOSEnum = 5,

            /// <summary>
            /// Enum APLICARESGATAINVESTIMENTOSEnum for APLICA_RESGATA_INVESTIMENTOS
            /// </summary>
            [EnumMember(Value = "APLICA_RESGATA_INVESTIMENTOS")]
            APLICARESGATAINVESTIMENTOSEnum = 6,

            /// <summary>
            /// Enum EXECUTAATIVAPASSIVAORDENSPAGAMENTOEnum for EXECUTA_ATIVA_PASSIVA_ORDENS_PAGAMENTO
            /// </summary>
            [EnumMember(Value = "EXECUTA_ATIVA_PASSIVA_ORDENS_PAGAMENTO")]
            EXECUTAATIVAPASSIVAORDENSPAGAMENTOEnum = 7,

            /// <summary>
            /// Enum DEPOSITAMOEDAESPECIECHEQUEEnum for DEPOSITA_MOEDA_ESPECIE_CHEQUE
            /// </summary>
            [EnumMember(Value = "DEPOSITA_MOEDA_ESPECIE_CHEQUE")]
            DEPOSITAMOEDAESPECIECHEQUEEnum = 8,

            /// <summary>
            /// Enum OPERACREDITOOUTROSSERVICOSACOMPANHAOPERACAOEnum for OPERA_CREDITO_OUTROS_SERVICOS_ACOMPANHA_OPERACAO
            /// </summary>
            [EnumMember(Value = "OPERA_CREDITO_OUTROS_SERVICOS_ACOMPANHA_OPERACAO")]
            OPERACREDITOOUTROSSERVICOSACOMPANHAOPERACAOEnum = 9,

            /// <summary>
            /// Enum CARTAOCREDITOEnum for CARTAO_CREDITO
            /// </summary>
            [EnumMember(Value = "CARTAO_CREDITO")]
            CARTAOCREDITOEnum = 10,

            /// <summary>
            /// Enum SEGUROSEnum for SEGUROS
            /// </summary>
            [EnumMember(Value = "SEGUROS")]
            SEGUROSEnum = 11,

            /// <summary>
            /// Enum OPERAARRENDAMENTOMERCANTILEnum for OPERA_ARRENDAMENTO_MERCANTIL
            /// </summary>
            [EnumMember(Value = "OPERA_ARRENDAMENTO_MERCANTIL")]
            OPERAARRENDAMENTOMERCANTILEnum = 12,

            /// <summary>
            /// Enum ABERTURACONTAPAGAMENTOPOSPAGAEnum for ABERTURA_CONTA_PAGAMENTO_POS_PAGA
            /// </summary>
            [EnumMember(Value = "ABERTURA_CONTA_PAGAMENTO_POS_PAGA")]
            ABERTURACONTAPAGAMENTOPOSPAGAEnum = 13,

            /// <summary>
            /// Enum COMPRAVENDEMOEDAESTRANGEIRAESPECIEEnum for COMPRA_VENDE_MOEDA_ESTRANGEIRA_ESPECIE
            /// </summary>
            [EnumMember(Value = "COMPRA_VENDE_MOEDA_ESTRANGEIRA_ESPECIE")]
            COMPRAVENDEMOEDAESTRANGEIRAESPECIEEnum = 14,

            /// <summary>
            /// Enum COMPRAVENDECHEQUECHEQUEVIAGEMCARGAMOEDAESTRANGEIRACARTAOPREPAGOEnum for COMPRA_VENDE_CHEQUE_CHEQUE_VIAGEM_CARGA_MOEDA_ESTRANGEIRA_CARTAO_PRE_PAGO
            /// </summary>
            [EnumMember(Value = "COMPRA_VENDE_CHEQUE_CHEQUE_VIAGEM_CARGA_MOEDA_ESTRANGEIRA_CARTAO_PRE_PAGO")]
            COMPRAVENDECHEQUECHEQUEVIAGEMCARGAMOEDAESTRANGEIRACARTAOPREPAGOEnum = 15,

            /// <summary>
            /// Enum COMPRAVENDEOUROEnum for COMPRA_VENDE_OURO
            /// </summary>
            [EnumMember(Value = "COMPRA_VENDE_OURO")]
            COMPRAVENDEOUROEnum = 16,

            /// <summary>
            /// Enum OUTROSPRODUTOSSERVICOSEnum for OUTROS_PRODUTOS_SERVICOS
            /// </summary>
            [EnumMember(Value = "OUTROS_PRODUTOS_SERVICOS")]
            OUTROSPRODUTOSSERVICOSEnum = 17,

            /// <summary>
            /// Enum CANCELAMENTOEnum for CANCELAMENTO
            /// </summary>
            [EnumMember(Value = "CANCELAMENTO")]
            CANCELAMENTOEnum = 18,

            /// <summary>
            /// Enum INFORMACOESEnum for INFORMACOES
            /// </summary>
            [EnumMember(Value = "INFORMACOES")]
            INFORMACOESEnum = 19,

            /// <summary>
            /// Enum RECLAMACOESEnum for RECLAMACOES
            /// </summary>
            [EnumMember(Value = "RECLAMACOES")]
            RECLAMACOESEnum = 20
        }

        /// <summary>
        /// Código dos Serviços efetivamente prestados pelo Terminal de Autoatendimento Compartilhado informado
        /// </summary>
        /// <value>Código dos Serviços efetivamente prestados pelo Terminal de Autoatendimento Compartilhado informado</value>
        [DataMember(Name = "code")]
        public CodeEnum? Code { get; set; }

        /// <summary>
        /// Texto livre para complementar informação relativa ao Serviço disponível, quando for preenchida a opção &#x27;OUTROS_PRODUTOS_SERVICOS&#x27;
        /// </summary>
        /// <value>Texto livre para complementar informação relativa ao Serviço disponível, quando for preenchida a opção &#x27;OUTROS_PRODUTOS_SERVICOS&#x27;</value>
        [DataMember(Name = "additionalInfo")]
        public string AdditionalInfo { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SharedAutomatedTellerMachinesServices {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Code: ").Append(Code).Append("\n");
            sb.Append("  AdditionalInfo: ").Append(AdditionalInfo).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((SharedAutomatedTellerMachinesServices)obj);
        }

        /// <summary>
        /// Returns true if SharedAutomatedTellerMachinesServices instances are equal
        /// </summary>
        /// <param name="other">Instance of SharedAutomatedTellerMachinesServices to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SharedAutomatedTellerMachinesServices other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    Name == other.Name ||
                    Name != null &&
                    Name.Equals(other.Name)
                ) &&
                (
                    Code == other.Code ||
                    Code != null &&
                    Code.Equals(other.Code)
                ) &&
                (
                    AdditionalInfo == other.AdditionalInfo ||
                    AdditionalInfo != null &&
                    AdditionalInfo.Equals(other.AdditionalInfo)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (Name != null)
                    hashCode = hashCode * 59 + Name.GetHashCode();
                if (Code != null)
                    hashCode = hashCode * 59 + Code.GetHashCode();
                if (AdditionalInfo != null)
                    hashCode = hashCode * 59 + AdditionalInfo.GetHashCode();
                return hashCode;
            }
        }

        #region Operators

#pragma warning disable 1591

        public static bool operator ==(SharedAutomatedTellerMachinesServices left, SharedAutomatedTellerMachinesServices right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(SharedAutomatedTellerMachinesServices left, SharedAutomatedTellerMachinesServices right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591

        #endregion Operators
    }
}